apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-secrets
  namespace: devsecops-platform
stringData:
  SLACK_WEBHOOK_URL: 'https://hooks.slack.com/services/REPLACE_ME/REPLACE_ME/REPLACE_ME'
  ALERT_EMAIL_TO: 'devops@example.com'
  ALERT_EMAIL_FROM: 'alertmanager@example.com'
  SMTP_SMARTHOST: 'smtp.gmail.com:587'
  SMTP_USERNAME: 'alertmanager@example.com'
  SMTP_PASSWORD: 'REPLACE_WITH_SMTP_PASSWORD'
  WEBHOOK_URL: 'https://hooks.example.com/alert'
  PAGE_EMAIL_TO: 'oncall@example.com'
  ESCALATION_EMAIL: 'incident-team@example.com'
