apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: devsecops-platform
  labels:
    app: grafana
spec:
  selector:
    app: grafana
  ports:
    - port: 4000
      targetPort: 3000
      protocol: TCP
  type: LoadBalancer
