apiVersion: v1
kind: ServiceAccount
metadata:
  name: ci-pipeline
  namespace: devsecops-platform

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ci-pipeline-role
  namespace: devsecops-platform
rules:
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create", "update", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ci-pipeline-binding
  namespace: devsecops-platform
subjects:
  - kind: ServiceAccount
    name: ci-pipeline
    namespace: devsecops-platform
roleRef:
  kind: Role
  name: ci-pipeline-role
  apiGroup: rbac.authorization.k8s.io
